[workspace]
channels = ["conda-forge"]
name = "screening-quality-control"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "python main.py"

[dependencies]
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
plotly = ">=6.3.1,<7"
scipy = ">=1.16.2,<2"

[pypi-dependencies]
bioio = ">=3.0.0,<4"
bioio-czi = ">=2.4.0, <3"
tdqm = ">=0.0.1, <0.0.2"
